# Generated by Django 5.1.6 on 2025-05-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
    ]
